import { describe, it, expect } from 'vitest';
import { xxh3_64str, computeMethodHash } from '../src/rpc-xxhash3.js';

// Test vectors generated by .NET System.IO.Hashing.XxHash3.HashToUInt64
// using deterministic seed (Random(42)) for reproducibility.
const XXH3_VECTORS: [string, bigint][] = [
    // Edge cases
    ['', 3244421341483603138n],
    ['a', 16629034431890738719n],
    ['ab', 12138170336140424028n],
    ['abc', 8696274497037089104n],
    ['hello', 10760762337991515389n],

    // RPC method names
    ['ITypeScriptTestService.Add:2', 12691831522105987730n],
    ['ITypeScriptTestComputeService.GetCounter:2', 11035071790144238159n],
    ['$sys.KeepAlive', 9250077078001227578n],
    ['$sys.Handshake', 3429007717786837182n],
    ['$sys.Ok', 13089043970195582208n],
    ['$sys.I', 17273334572127442430n],
    ['$sys.B', 8919635718310672040n],
    ['$sys.End', 15994401423933406906n],

    // Length boundaries
    ['xxxxxxxxxxxxxxxx', 16102337951141043935n], // 16 bytes
    ['yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy', 9934995586273875345n], // 32 bytes
    ['z'.repeat(64), 1504468004190730616n],
    ['w'.repeat(128), 1998539121132424851n],
    ['v'.repeat(256), 15805419833403538331n],

    // Unicode
    ['hello\0world', 7387166017187604645n],
    ['\u3053\u3093\u306b\u3061\u306f', 3973994090912779455n], // こんにちは
    ['\uD83C\uDF89\uD83D\uDD25\uD83D\uDCAF', 18404621122577759711n], // 🎉🔥💯

    // Varying lengths (from .NET Random(42))
    ['_', 4575667007673887251n],
    ['-+', 11931608255360411211n],
    ['Q08', 10386375751172249384n],
    ['dP0h', 5394984039241382149n],
    ['68P>D', 16555712099796165873n],
    ['8Q#mVE', 6268088101325028467n],
    ['.(bmS$c', 8730866342717046434n],
];

// Test vectors for computeMethodHash (matches .NET RpcMethodRef.ComputeHashCode)
const METHOD_HASH_VECTORS: [string, number][] = [
    ['ITypeScriptTestService.Add:2', 368407966],
    ['ITypeScriptTestService.Add:3', -1430677206],
    ['ITypeScriptTestService.Greet:1', -949795572],
    ['ITypeScriptTestComputeService.GetCounter:2', -24618632],
    ['$sys.KeepAlive', -2104790457],
    ['$sys.Handshake', -386831013],
    ['$sys.Ok', 225426712],
    ['$sys.I', -52950668],
    ['$sys.B', -1197916366],
    ['$sys.End', -1224767354],
    ['$sys.Ack', -1793137119],
    ['$sys.AckEnd', -1225014432],
    ['$sys.Cancel', 1995375879],
    ['$sys.Error', -1844021631],
    ['', 385620285],
    ['a', 1823657521],
    ['X', -914284492],
];

describe('XXH3-64', () => {
    it('should match .NET XxHash3.HashToUInt64 for all test vectors', () => {
        for (const [input, expected] of XXH3_VECTORS) {
            const actual = xxh3_64str(input);
            expect(actual).toBe(
                expected,
                `xxh3_64str("${input.length > 30 ? input.substring(0, 30) + '...' : input}") = ${actual}, expected ${expected}`
            );
        }
    });

    it('should match .NET for empty input', () => {
        expect(xxh3_64str('')).toBe(3244421341483603138n);
    });

    it('should match .NET for single character', () => {
        expect(xxh3_64str('a')).toBe(16629034431890738719n);
    });

    it('should match .NET for typical RPC method names', () => {
        expect(xxh3_64str('$sys.KeepAlive')).toBe(9250077078001227578n);
        expect(xxh3_64str('ITypeScriptTestService.Add:2')).toBe(
            12691831522105987730n
        );
    });

    it('should handle unicode correctly', () => {
        expect(xxh3_64str('\u3053\u3093\u306b\u3061\u306f')).toBe(
            3973994090912779455n
        );
    });

    it('should handle null bytes in input', () => {
        expect(xxh3_64str('hello\0world')).toBe(7387166017187604645n);
    });
});

describe('computeMethodHash', () => {
    it('should match .NET RpcMethodRef.ComputeHashCode for all test vectors', () => {
        for (const [method, expected] of METHOD_HASH_VECTORS) {
            const actual = computeMethodHash(method);
            expect(actual).toBe(
                expected,
                `computeMethodHash("${method}") = ${actual}, expected ${expected}`
            );
        }
    });

    it('should return consistent results for the same input', () => {
        const h1 = computeMethodHash('$sys.Ok');
        const h2 = computeMethodHash('$sys.Ok');
        expect(h1).toBe(h2);
    });

    it('should return different hashes for different methods', () => {
        const h1 = computeMethodHash('$sys.Ok');
        const h2 = computeMethodHash('$sys.Error');
        expect(h1).not.toBe(h2);
    });

    it('should return different hashes for overloads with different arity', () => {
        const h2 = computeMethodHash('ITypeScriptTestService.Add:2');
        const h3 = computeMethodHash('ITypeScriptTestService.Add:3');
        expect(h2).not.toBe(h3);
    });
});
