ignore:
  - "tests"
  - "samples"
  - "src/**/Compatibility"
  - "src/Stl.Interception/ArgumentList-Generated.cs" # It's enough to cover just one generic variant, so we assume it's fully covered
  - "src/Stl.Fusion.Blazor" # No tests yet - let's assume this is tested via apps
  - "src/Stl.Redis" # Redis tests are there, but they don't run on GitHub
  - "src/Stl.Testing"
  - "src/Stl.DependencyInjection.Extras"
coverage:
  precision: 2
  round: nearest
  range: "60...100"
  status:
    project:
      default:
        target: auto
        threshold: 2%
        base: auto 
        branches: 
          - master
        if_ci_failed: error # success, failure, error, ignore
        only_pulls: false
