ignore:
  - "tests"
  - "samples"
  - "src/**/Compatibility"
  - "src/Stl.Testing"
  - "src/Stl.DependencyInjection.Extras"
coverage:
  precision: 2
  round: down
  range: "65...100"
  status:
    project:
      default:
        target: auto
        threshold: 2%
        base: auto 
        branches: 
          - master
        if_ci_failed: error # success, failure, error, ignore
        only_pulls: false
