version: '3.4'
services:
  redis:
    image: "redis:6.2.6-alpine3.14"
    ports:
     - "6379:6379"
  postgres:
    image: "postgres:14.0-alpine3.14"
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "password"
    ports:
     - "5432:5432"
    entrypoint: ["docker-entrypoint.sh", "-c", "shared_buffers=256MB", "-c", "max_connections=1000"]
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
  sqlserver:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "SqlServer1" # Min. 8 chars, upper-lower-digit/symbol
      ACCEPT_EULA: "Y"
    ports:
     - "1433:1433"
