name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Avoid shallow clone for Nerdbank.GitVersioning
          fetch-depth: 0

      - run: "echo 'SemVer2: ${{ steps.nbgv.outputs.SemVer2 }}'"

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Install .NET workloads
        run: dotnet workload install wasm-tools aspire

      - uses: dotnet/nbgv@master
        id: nbgv
        with:
          setAllVars: true
          setCommonVars: true

      - name: Restore NuGet Packages & Tools
        run: dotnet run --project build -c Release --no-launch-profile -- restore restore-tools

      - name: Build
        run: dotnet run --project build -c Release --no-launch-profile -- --configuration Debug --framework net8.0 build

      - name: Run tests
        run: dotnet run --project build -c Release --no-launch-profile -- --configuration Debug --framework net8.0 coverage

      - name: Codecov
        uses: codecov/codecov-action@v1.0.13
        with:
          name: codecov-bot
          file: artifacts/tests/output/*.xml
          flags: unit
          # fail_ci_if_error: true
